// Code generated by go-bindata.
// sources:
// src/util/assets/.app.js.swp
// src/util/assets/LICENSE
// src/util/assets/README.md
// src/util/assets/app.js
// src/util/assets/bootstrap.min.css
// src/util/assets/bootstrap.min.js
// src/util/assets/index.html
// src/util/assets/jquery-2.2.4.min.js
// src/util/assets/jquery.jsonbrowser.css
// src/util/assets/jquery.jsonbrowser.js
// src/util/assets/underscore-min.js
// DO NOT EDIT!

package util

import (
	"net/http"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// srcUtilAssetsAppJsSwp reads file data from disk. It returns an error on failure.
func srcUtilAssetsAppJsSwp() (*asset, error) {
	path := "/Users/slawosz/code/api-booster/src/util/assets/.app.js.swp"
	name := "src/util/assets/.app.js.swp"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcUtilAssetsLicense reads file data from disk. It returns an error on failure.
func srcUtilAssetsLicense() (*asset, error) {
	path := "/Users/slawosz/code/api-booster/src/util/assets/LICENSE"
	name := "src/util/assets/LICENSE"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcUtilAssetsReadmeMd reads file data from disk. It returns an error on failure.
func srcUtilAssetsReadmeMd() (*asset, error) {
	path := "/Users/slawosz/code/api-booster/src/util/assets/README.md"
	name := "src/util/assets/README.md"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcUtilAssetsAppJs reads file data from disk. It returns an error on failure.
func srcUtilAssetsAppJs() (*asset, error) {
	path := "/Users/slawosz/code/api-booster/src/util/assets/app.js"
	name := "src/util/assets/app.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcUtilAssetsBootstrapMinCss reads file data from disk. It returns an error on failure.
func srcUtilAssetsBootstrapMinCss() (*asset, error) {
	path := "/Users/slawosz/code/api-booster/src/util/assets/bootstrap.min.css"
	name := "src/util/assets/bootstrap.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcUtilAssetsBootstrapMinJs reads file data from disk. It returns an error on failure.
func srcUtilAssetsBootstrapMinJs() (*asset, error) {
	path := "/Users/slawosz/code/api-booster/src/util/assets/bootstrap.min.js"
	name := "src/util/assets/bootstrap.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcUtilAssetsIndexHtml reads file data from disk. It returns an error on failure.
func srcUtilAssetsIndexHtml() (*asset, error) {
	path := "/Users/slawosz/code/api-booster/src/util/assets/index.html"
	name := "src/util/assets/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcUtilAssetsJquery224MinJs reads file data from disk. It returns an error on failure.
func srcUtilAssetsJquery224MinJs() (*asset, error) {
	path := "/Users/slawosz/code/api-booster/src/util/assets/jquery-2.2.4.min.js"
	name := "src/util/assets/jquery-2.2.4.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcUtilAssetsJqueryJsonbrowserCss reads file data from disk. It returns an error on failure.
func srcUtilAssetsJqueryJsonbrowserCss() (*asset, error) {
	path := "/Users/slawosz/code/api-booster/src/util/assets/jquery.jsonbrowser.css"
	name := "src/util/assets/jquery.jsonbrowser.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcUtilAssetsJqueryJsonbrowserJs reads file data from disk. It returns an error on failure.
func srcUtilAssetsJqueryJsonbrowserJs() (*asset, error) {
	path := "/Users/slawosz/code/api-booster/src/util/assets/jquery.jsonbrowser.js"
	name := "src/util/assets/jquery.jsonbrowser.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcUtilAssetsUnderscoreMinJs reads file data from disk. It returns an error on failure.
func srcUtilAssetsUnderscoreMinJs() (*asset, error) {
	path := "/Users/slawosz/code/api-booster/src/util/assets/underscore-min.js"
	name := "src/util/assets/underscore-min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"src/util/assets/.app.js.swp": srcUtilAssetsAppJsSwp,
	"src/util/assets/LICENSE": srcUtilAssetsLicense,
	"src/util/assets/README.md": srcUtilAssetsReadmeMd,
	"src/util/assets/app.js": srcUtilAssetsAppJs,
	"src/util/assets/bootstrap.min.css": srcUtilAssetsBootstrapMinCss,
	"src/util/assets/bootstrap.min.js": srcUtilAssetsBootstrapMinJs,
	"src/util/assets/index.html": srcUtilAssetsIndexHtml,
	"src/util/assets/jquery-2.2.4.min.js": srcUtilAssetsJquery224MinJs,
	"src/util/assets/jquery.jsonbrowser.css": srcUtilAssetsJqueryJsonbrowserCss,
	"src/util/assets/jquery.jsonbrowser.js": srcUtilAssetsJqueryJsonbrowserJs,
	"src/util/assets/underscore-min.js": srcUtilAssetsUnderscoreMinJs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"src": &bintree{nil, map[string]*bintree{
		"util": &bintree{nil, map[string]*bintree{
			"assets": &bintree{nil, map[string]*bintree{
				".app.js.swp": &bintree{srcUtilAssetsAppJsSwp, map[string]*bintree{}},
				"LICENSE": &bintree{srcUtilAssetsLicense, map[string]*bintree{}},
				"README.md": &bintree{srcUtilAssetsReadmeMd, map[string]*bintree{}},
				"app.js": &bintree{srcUtilAssetsAppJs, map[string]*bintree{}},
				"bootstrap.min.css": &bintree{srcUtilAssetsBootstrapMinCss, map[string]*bintree{}},
				"bootstrap.min.js": &bintree{srcUtilAssetsBootstrapMinJs, map[string]*bintree{}},
				"index.html": &bintree{srcUtilAssetsIndexHtml, map[string]*bintree{}},
				"jquery-2.2.4.min.js": &bintree{srcUtilAssetsJquery224MinJs, map[string]*bintree{}},
				"jquery.jsonbrowser.css": &bintree{srcUtilAssetsJqueryJsonbrowserCss, map[string]*bintree{}},
				"jquery.jsonbrowser.js": &bintree{srcUtilAssetsJqueryJsonbrowserJs, map[string]*bintree{}},
				"underscore-min.js": &bintree{srcUtilAssetsUnderscoreMinJs, map[string]*bintree{}},
			}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}


func assetFS() http.FileSystem {
	for k := range _bintree.Children {
		return http.Dir(k)
	}
	panic("unreachable")
}
